# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a1eb64553cc7c9eca0b3afe35a88de4f"
name = "zapchat"
application_url = "https://zapchat.solnix.store"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes"

[auth]
redirect_urls = [ "https://zapchat.solnix.store/api/auth/callback" ]

[webhooks.privacy_compliance]
customer_deletion_url = "https://zapchat.solnix.store/api/webhooks"
customer_data_request_url = "https://zapchat.solnix.store/api/webhooks"
shop_deletion_url = "https://zapchat.solnix.store/api/webhooks"
