# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f8878e48c46de19d79c0fa5d9f9cb888"
name = "chatlink"
application_url = "https://chatlink.onkra.online"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes"

[auth]
redirect_urls = [ "https://chatlink.onkra.online/api/auth/callback" ]

[webhooks.privacy_compliance]
customer_deletion_url = "https://chatlink.onkra.online/api/webhooks"
customer_data_request_url = "https://chatlink.onkra.online/api/webhooks"
shop_deletion_url = "https://chatlink.onkra.online/api/webhooks"
